@startuml C2_Альтернативное_Решение_Свиноводство

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контейнерная диаграмма системы мониторинга свиноводства - Альтернативное решение

'Container_Boundary(пользователи, "Пользователи") {
    Person(директор, "Директор хозяйства", "Управление через веб-портал")
    Person(ветеринар, "Ветеринар", "Отслеживает здоровье поголовья")
    Person(оператор, "Оператор фермы", "Контролирует состояние животных и оборудования")
    Person(работник, "Работник фермы", "Получает локальные уведомления")
    Person(техник, "Техник", "Обслуживает оборудование")
'}

' Внешние сервисы
System_Ext(сервис_уведомлений, "Сервис уведомлений", "SMS/Push/Email")
System_Ext(ml_платформа, "ML Platform", "Платформа машинного обучения партнера")

' Существующая инфраструктура
System_Ext(существ_kafka, "Apache Kafka", "Существующая шина данных АгроТех")
System_Ext(существ_erp, "1С:Агро", "ERP система компании")
System_Ext(существ_dwh, "ClickHouse", "Корпоративное хранилище данных")
System_Ext(существ_datalake, "MinIO Data Lake", "Хранилище неструктурированных данных")

' Система
'System_Boundary(мониторинг_свиней, "Система мониторинга свиноводства") {
    Container(новое_mobile, "Веб-приложение свиноводства", "PWA - сайт, который можно установить как приложение, и использовать как основу для полноценного приложения")

    ' Центр
    Container_Boundary(центр_система, "Центральная система мониторинга", "Агрегация данных, аналитика, управление") {
        ' Шина событий
        Container(nats_центр, "Брокер сообщений", "NATS JetStream", "Команды, телеметрия, метаданные")

        Container(api_центр, "API шлюз", "Node.js", "Единая точка входа для API")

        Container_Boundary(агенты, "Взаимодействие с агентами") {
            Container(агент_центра, "Агент центра", "Node.js", "Резервный канал синхронизации")
            Container(центр_синхронизации, "Центр синхронизации", "Node.js", "Центр синхронизации с агентами")
            Container(событийный_шлюз, "Событийный шлюз", "Node.js", "Агрегация и распределение потока данных агентов")
            ContainerDb(бд_настроек, "БД настроек", "PostgreSQL", "Центральное хранилище")
        }

        Container_Boundary(мониторинг, "Мониторинг") {
            Container(сбор_метрик, "Сбор метрик", "Node.js, Prometheus", "Сбор метрик")
            ContainerDb(хранение_метрик, "БД временных рядов", "TimescaleDB", "Хранение метрик")
        }

        Container_Boundary(аналитика, "Аналитика") {
            Container(агрегация_данных, "Агрегация данных", "Apache Spark")
            Container(отчёты, "Отчёты", "Node.js, Python", "Генерация отчётов")
        }

        Container_Boundary(свиноводство, "Свиноводство") {
            Container(здоровье, "Здоровье", "Python", "Анализ здоровья")
            Container(кормление, "Кормление", "Python", "Оптимизация кормления")
            Container(управление_свиноводством, "Свиноводство", "Node.js", "Управление данными о свиньях")
            ContainerDb(бд_свиноводства, "БД свиноводства", "PostgreSQL", "БД свиноводства")
        }

        Container_Boundary(аутентификация, "Аутентификация") {
            Container(api_авторизации, "Сервис авторизации", "Node.js, OAuth2", "Управление пользователями")
            ContainerDb(бд_аутентификации, "БД Авторизации", "PostgreSQL", "БД Аутентификации")
        }

        ' Обработка данных через NATS
        BiRel(nats_центр, событийный_шлюз, "Показания датчиков, события и команды")
        BiRel(nats_центр, сбор_метрик, "Показания датчиков, события и команды")
        BiRel(nats_центр, управление_свиноводством, "Показатели и события\nКоманды")
        Rel(nats_центр, отчёты, "Получение аналитики")
        Rel(api_центр, nats_центр, "Показатели, данные и события\nКоманды")

        ' Работа с хранилищем
        BiRel(api_авторизации, бд_аутентификации, "CRUD", "SQL")
        BiRel(центр_синхронизации, событийный_шлюз, "Сохранение показаний датчиков и истории событий/команд", "gRPC")
        Rel(событийный_шлюз, агент_центра, "Сохранение показаний датчиков и истории событий/команд", "gRPC")
        Rel(центр_синхронизации, бд_настроек, "CRUD", "SQL")
        Rel(агент_центра, бд_настроек, "CRUD", "SQL")

        ' Аналитика
        Rel(сбор_метрик, хранение_метрик, "Сохранение метрик", "SQL")
        Rel(хранение_метрик, агрегация_данных, "Чтение метрик", "SQL")
        Rel(отчёты, агрегация_данных, "Запрос данныз", "gRPC")
        Rel(агрегация_данных, существ_dwh, "Агрегация данных", "SQL")

        ' Внешние взаимодействия
        Rel(событийный_шлюз, сервис_уведомлений, "Уведомления", "REST API")

        ' Свиноводство
        Rel(здоровье, управление_свиноводством, "Анализ здоровья", "gRPC")
        Rel(кормление, управление_свиноводством, "CRUD", "gRPC")
        Rel(управление_свиноводством, бд_свиноводства, "CRUD", "SQL")
        Rel(управление_свиноводством, хранение_метрик, "Чтение метрик", "SQL")

        ' Взаимодействие с пользователями
        Rel(новое_mobile, api_авторизации, "Авторизация", "HTTPS OAuth2")
        Rel(новое_mobile, api_центр, "Дополнительный канал", "HTTPS/WebSocket")
    }

    ' Агент фермы
    Container_Boundary(агент_фермы, "Агент фермы") {
        ' Оборудование
        Container_Boundary(iot_фермы, "IoT фермы") {
            System_Ext(камеры, "Камеры", "IP-камеры")
            System_Ext(датчики, "Датчики", "Показатели воды и другие датчики: уровни корма и воды, pH, температура, мутность воды и т.д.")
            System_Ext(агрегаты, "Исполнительные механизмы", "Поилки, кормушки и т.д.")
        }

        ' Управление
        Container_Boundary(api_агента, "API") {
            Container(api_агент, "API шлюз", "Node.js", "Единая точка входа для API")
            Container(redis_агент, "Кэш", "Redis", "Кэш запросов")
        }

        ' Сервисы взаимодействия с оборудованием
        Container(устройства, "Управление устройствами", "C++/Python", "Управление IoT устройствами")
        Container(видео_шлюз, "Видео шлюз", "Python, OpenCV", "Принимает RTSP, предобработка видео и получение метаданные")
        ' Шина событий
        Container(nats_агент, "Брокер сообщений", "NATS", "Команды, телеметрия, метаданные")
        ' ИИ
        Container(ml_сервис, "ML-сервис", "Python, TensorFlow", "Анализ кадров, компьютерное зрение")
        ' Управление
        Container(iot_шлюз, "IoT шлюз", "Node-RED", "Базовые автоматизации")
        Container(edge_шлюз, "Агент фермы", "Node.js", "Локальный сервис управления")
        ' Хранилище
        ContainerDb(локальное_хранилище, "Локальное хранилище", "SQLite + MinIO", "Ограниченное локальное хранилище данных")
        Container(агент_синхронизации, "Агент синхронизации", "Node.js", "Агент синхронизации с центром")

        ' Подключения устройств
        Rel(датчики, устройства, "Показания датчиков", "Modbus/I2C/I2S/UART/ADC")
        Rel(устройства, агрегаты, "Передача команд", "Modbus/UART")

        ' Видео потоки
        Rel(камеры, видео_шлюз, "RTSP/HLS", "прямое соединение\n(видео 1-50 Мбит/с)")
        Rel(видео_шлюз, nats_агент, "Метаданные камер", "cameras.metadata.*")
        Rel(видео_шлюз, ml_сервис, "Видеопоток", "in-memory")
        Rel(ml_сервис, nats_агент, "События из видео", "cameras.events.*")

        ' Обработка данных через NATS
        BiRel(nats_агент, edge_шлюз, "Показатели, события\nОтправка команд")
        BiRel(nats_агент, iot_шлюз, "Показатели, события\nОтправка команд")

        ' Работа с хранилищем
        Rel(видео_шлюз, локальное_хранилище, "Архивирование видео", "RTSP/S3")
        Rel(локальное_хранилище, edge_шлюз, "Сохранение данных\nЧтение настроек", "gRPC")
        BiRel(локальное_хранилище, iot_шлюз, "Чтение настроек\nСохранение данных", "gRPC")
        BiRel(локальное_хранилище, агент_синхронизации, "Отправка данных\nСинхронизация настроек", "gRPC")

        ' Внутренние взаимодействия
        BiRel(устройства, nats_агент, "Показания датчиков\nОтправка команд", "sensors.*\ndevices.*")
        BiRel(устройства, nats_агент, "Показания датчиков\nОтправка команд", "*.*")

        ' Внешние взаимодействия
        Rel(ml_платформа, ml_сервис, "Загрузка модели", "gRPC")
        Rel(api_агент, edge_шлюз, "Отложенная синхронизация", "gRPC")
        Rel(edge_шлюз, существ_datalake, "Сохраняет видео и сырые данные", "S3 API")

        ' Взаимодействие с пользователями
        Rel(новое_mobile, api_агент, "Оперативный канал", "HTTPS/WebSocket")
        Rel(redis_агент, api_агент, "Работа с кэшем")
    }

    ' Резервный канал
    BiRel(edge_шлюз, агент_центра, "Резервный канал", "gRPC")
'}

BiRel(агент_синхронизации, существ_kafka, "Отложенная синхронизация", "Kafka Protocol")
BiRel(центр_синхронизации, существ_kafka, "Отложенная синхронизация", "Kafka Protocol")

' Интеграция в существующею систему
Rel(управление_свиноводством, существ_erp, "Синхронизация данных о поголовье и кормах", "REST API")

' Пользовательские взаимодействия
'Rel(пользователи, новое_mobile, "Локальный мониторинг и управление", "Web UI")
Rel(директор, новое_mobile, "Локальный мониторинг и управление", "Web UI")
Rel(ветеринар, новое_mobile, "Локальный мониторинг и управление", "Web UI")
Rel(оператор, новое_mobile, "Локальный мониторинг и управление", "Web UI")
Rel(работник, новое_mobile, "Локальный мониторинг и управление", "Web UI")
Rel(техник, новое_mobile, "Локальный мониторинг и управление", "Web UI")

@enduml