@startuml C2_Основное_Решение_Свиноводство

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контейнерная диаграмма системы мониторинга свиноводства - Основное решение

Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(ветеринар, "Ветеринар", "Отслеживает здоровье поголовья")
Person(оператор, "Оператор фермы", "Контролирует состояние животных и оборудования")
Person(работник, "Работник фермы", "Получает локальные уведомления")
Person(техник, "Техник", "Обслуживает оборудование")

' Внешние сервисы
System_Ext(сервис_уведомлений, "Сервис уведомлений", "SMS/Push/Email")
System_Ext(ml_платформа, "ML Platform", "Платформа машинного обучения партнера")

' Существующая инфраструктура
System_Ext(существ_kafka, "Apache Kafka", "Существующая шина данных АгроТех")
System_Ext(существ_веб_портал, "Веб-портал управления хозяйством", "React")
System_Ext(существ_mobile, "Мобильное приложение АгроТех", "Существующее приложение Flutter")
System_Ext(существ_erp, "1С:Агро", "ERP система компании")
System_Ext(существ_dwh, "ClickHouse", "Корпоративное хранилище данных")
System_Ext(существ_datalake, "MinIO Data Lake", "Хранилище неструктурированных данных")

' Система
'System_Boundary(мониторинг_свиней, "Система мониторинга свиноводства") {
    Container_Boundary(пользователи, "Взаимодействие с пользователями") {
        Container(веб_портал, "Веб-портал", "React модуль", "Расширение для портала АгроТех")
        Container(мобил_приложение, "Мобильное приложение", "Flutter модуль", "Расширение для мобильного приложения")
    }

    ' Центр
    Container_Boundary(центр_система, "Центральная система мониторинга", "Агрегация данных, аналитика, управление") {
        ' Шина событий
        Container(nats_центр, "Брокер сообщений", "NATS", "Команды, телеметрия, метаданные")
        ' Управление
        Container(api_шлюз, "API шлюз", "Node.js", "Единая точка входа для API")

        Container_Boundary(агенты, "Взаимодействие с агентами") {
            Container(событийный_шлюз, "Событийный шлюз", "Node.js", "Агрегация и распределение потока данных агентов")
            Container(центр_синхронизации, "Центр синхронизации", "Node.js", "Центр синхронизации с агентами")
            ContainerDb(бд_настроек, "Центральное хранилище", "PostgreSQL", "Основная БД системы")
        }

        Container_Boundary(мониторинг, "Мониторинг") {
            Container(сбор_метрик, "Сбор метрик", "Node.js, Prometheus", "Сбор метрик")
            ContainerDb(хранение_метрик, "БД временных рядов", "TimescaleDB", "Хранение метрик")
        }

        Container_Boundary(аналитика, "Аналитика") {
            Container(агрегация_данных, "Агрегация данных", "Apache Spark")
            Container(отчёты, "Отчёты", "Node.js, Python", "Генерация отчётов")
        }

        Container_Boundary(свиноводство, "Свиноводство") {
            Container(здоровье, "Здоровье", "Python", "Анализ здоровья")
            Container(кормление, "Кормление", "Python", "Оптимизация кормления")
            Container(управление_свиноводством, "Свиноводство", "Node.js", "Управление данными о свиньях")
            ContainerDb(бд_свиноводства, "БД свиноводства", "PostgreSQL", "БД свиноводства")
        }

        ' Обработка данных через NATS
        BiRel(nats_центр, событийный_шлюз, "Показания датчиков, события и команды")
        BiRel(nats_центр, сбор_метрик, "Показания датчиков, события и команды")
        BiRel(nats_центр, управление_свиноводством, "Показатели и события\nКоманды")
        BiRel(nats_центр, отчёты, "Получение отчётов")
        BiRel(api_шлюз, nats_центр, "Показатели, данные и события\nКоманды")

        ' Работа с хранилищем
        Rel(центр_синхронизации, событийный_шлюз, "Сохранение показаний датчиков и истории событий/команд", "SQL")
        BiRel(центр_синхронизации, бд_настроек, "Синхронизация настроек с агентами ферм", "SQL")

        ' Аналитика
        Rel(сбор_метрик, хранение_метрик, "Сохранение метрик", "SQL")
        Rel(хранение_метрик, агрегация_данных, "Чтение метрик", "SQL")
        Rel(отчёты, агрегация_данных, "Запрос данныз", "gRPC")
        Rel(агрегация_данных, существ_dwh, "Агрегация данных", "SQL")

        ' Внешние взаимодействия
        BiRel(центр_синхронизации, существ_kafka, "Отложенная синхронизация", "Kafka Protocol")
        Rel(событийный_шлюз, сервис_уведомлений, "Уведомления", "REST API")

        ' Свиноводство
        Rel(здоровье, управление_свиноводством, "Анализ здоровья", "gRPC")
        Rel(кормление, управление_свиноводством, "CRUD", "gRPC")
        BiRel(управление_свиноводством, бд_свиноводства, "CRUD", "SQL")

        ' Взаимодействие с пользователями
        Rel(веб_портал, api_шлюз, "API запросы", "HTTPS/WebSocket")
        Rel(мобил_приложение, api_шлюз, "API запросы", "HTTPS")
    }

    ' Агент фермы
    Container_Boundary(агент_фермы, "Агент фермы") {
        ' Оборудование
        Container_Boundary(iot_фермы, "IoT фермы") {
            System_Ext(камеры, "Камеры", "IP-камеры")
            System_Ext(датчики, "Датчики", "Показатели воды и другие датчики: уровни корма и воды, pH, температура, мутность воды и т.д.")
            System_Ext(агрегаты, "Исполнительные механизмы", "Поилки, кормушки и т.д.")
        }

        ' Сервисы взаимодействия с оборудованием
        Container(устройства, "Управление устройствами", "C++/Python", "Управление IoT устройствами")
        Container(видео_шлюз, "Видео шлюз", "Python, OpenCV", "Принимает RTSP, предобработка видео и получение метаданные")
        ' Шина событий
        Container(nats_агент, "Брокер сообщений", "NATS", "Команды, телеметрия, метаданные")
        ' ИИ
        Container(ml_сервис, "ML-сервис", "Python, TensorFlow", "Анализ кадров, компьютерное зрение")
        ' Управление
        Container(iot_шлюз, "IoT шлюз", "Node-RED", "Базовые автоматизации")
        ' Хранилище
        ContainerDb(локальное_хранилище, "Локальное хранилище", "SQLite + MinIO", "Ограниченное локальное хранилище данных")
        Container(агент_синхронизации, "Агент синхронизации", "Node.js", "Агент синхронизации с центром")

        ' Подключения устройств
        Rel(датчики, устройства, "Показания датчиков", "Modbus/I2C/I2S/UART/ADC")
        Rel(устройства, агрегаты, "Передача команд", "Modbus/UART")

        ' Видео потоки
        Rel(камеры, видео_шлюз, "RTSP/HLS", "прямое соединение\n(видео 1-50 Мбит/с)")
        Rel(видео_шлюз, nats_агент, "Метаданные камер", "cameras.metadata.*")
        Rel(видео_шлюз, ml_сервис, "Видеопоток", "in-memory")
        Rel(ml_сервис, nats_агент, "События из видео", "cameras.events.*")
        BiRel(nats_агент, агент_синхронизации, "Оперативная передача показателей, событий и команд", "*.*")

        ' Обработка данных через NATS
        BiRel(nats_агент, iot_шлюз, "Получение сообщений\nОтправка команд")

        ' Работа с хранилищем
        Rel(видео_шлюз, локальное_хранилище, "Архивирование видео", "RTSP/S3")
        BiRel(локальное_хранилище, iot_шлюз, "Чтение настроек\nСохранение данных", "SQL")
        BiRel(локальное_хранилище, агент_синхронизации, "Синхронизация настроек\nЧтение данных", "SQL, S3")
        Rel(агент_синхронизации, существ_datalake, "Сохраняет видео и сырые данные", "S3 API")

        ' Внутренние взаимодействия
        BiRel(устройства, nats_агент, "Показания датчиков\nОтправка команд", "sensors.*\ndevices.*")

        ' Внешние взаимодействия
        Rel(ml_платформа, ml_сервис, "Загрузка модели", "gRPC")
        BiRel(агент_синхронизации, существ_kafka, "Синхронизация", "Kafka Protocol")
        
    }
'}

' Интеграция в существующею систему
Rel(существ_mobile, мобил_приложение, "Интеграция")
Rel(существ_веб_портал, веб_портал, "Интеграция")
Rel(управление_свиноводством, существ_erp, "Синхронизация данных о поголовье и кормах", "REST API")

' Пользовательские взаимодействия
Rel(директор, существ_веб_портал, "Локальный мониторинг и управление", "Web UI")
Rel(ветеринар, существ_веб_портал, "Анализ здоровья животных", "Web UI")
Rel(работник, существ_mobile, "Получает локальные оповещения")
Rel(оператор, существ_mobile, "Локальный мониторинг и управление")
Rel(техник, существ_mobile, "Мониторинг оборудования")

@enduml